config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'page', to: 'pages#show'
  patch 'page', to: 'pages#update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pages, only: [:edit]

  resources :products, only: [:show, :new, :create, :index, :edit, :destroy,:update ]
  get '/products_in', to: "products#index_in", as: :products_in
  resources :journals, only: [:show, :new, :create, :index, :edit, :destroy,:update ]
  resources :philosophies, only: [:index, :edit, :update ]
  resources :stockists, only: [:new, :create, :index, :edit, :destroy,:update ]
  resources :cities, only: [:destroy, :new, :create]
  resources :faqs, only: [:destroy, :new, :create, :index, :edit, :update]

  # get '/404', to: "errors#not_found"
  # get '/422', to: "errors#unacceptable"
  # get '/500', to: "errors#internal_error"
end

app/models/faq.rb
class Faq < ApplicationRecord
  belongs_to :user
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_faq, only: [:edit, :update, :destroy]

  def index
    @faqs = Faq.where("statut = ?", "active" ).order(created_at: :asc)
  end

  def show
  end

  def new
    @faq = Faq.new
  end

  def create
    @faq = Faq.new(faq_params)
    @faq.user_id = current_user.id
    @faq.statut = "active"
    if @faq.save
      redirect_to faqs_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @faq.update(faq_params)
      redirect_to faqs_path
    else
      render :edit
    end
  end

  def destroy
    @faq.statut = "deleted"
    @faq.save
    redirect_to faqs_path
  end

  private

  def faq_params
    params.require(:faq).permit(
      :question,
      :answer,
    )
  end

  def set_faq
    @faq = Faq.find(params[:id])
  end
end

app/views/faqs/edit.html.erb
<h1 class="text-center mt-5 mb-4">Add a new FAQ</h1>
<div class="container center">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6 col-lg-6">
      <div class="center">
        <%= simple_form_for [@faq] do |f| %>
          <%= f.input :question %>
          <%= f.input :answer %>
          <%= f.submit "Update", class: "btn btn btn-yellow-mustard mb-2" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/faqs/index.html.erb
<div class="pb-5" style="background-color: rgba(196, 196, 196, 0.15); min-height: 140vh">
  <div class="container">
    <h3 class="hide-on-small text-center py-5" style="font-size: 30px">FAQ</h3>
    <h5 class="hide-on-large text-center py-5" style="">FAQ</h5>
    <div class="row">
      <% @faqs.each do |faq| %>
        <div class="col-12 col-md-6 mt-4">
          <div class="d-flex">
            <p style="font-weight: bolder; font-size: 22px"><%= faq.question %></p>
            <% if user_signed_in? %>
              <%= link_to "", edit_faq_path(faq), class:"fas fa-edit ml-2 mt-2" %>
              <h5 class="mb-5">/</h5>
              <%= link_to '', faq_path(faq), method: :delete, data: { confirm: 'Are you sure you cant to delete this product ?'}, class:"fas fa-trash mt-2"  %>
            <% end %>
          </div>
          <p><%= simple_format(faq.answer, class:"text-justify") %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/faqs/new.html.erb
<h1 class="text-center mt-5 mb-4">Add a new FAQ</h1>
<div class="container center">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6 col-lg-6">
      <div class="center">
        <%= simple_form_for [@faq] do |f| %>
          <%= f.input :question %>
          <%= f.input :answer %>
          <%= f.submit "Create", class: "btn btn btn-yellow-mustard mb-2" %>
        <% end %>
      </div>
    </div>
  </div>
</div>