config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'page', to: 'pages#show'
  patch 'page', to: 'pages#update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pages, only: [:edit]

  resources :products, only: [:show, :new, :create, :index, :edit, :destroy,:update ]
  get '/products_in', to: "products#index_in", as: :products_in
  resources :journals, only: [:show, :new, :create, :index, :edit, :destroy,:update ]
  resources :philosophies, only: [:index, :edit, :update ]
  resources :stockists, only: [:new, :create, :index, :edit, :destroy,:update ]
  resources :cities, only: [:destroy, :new, :create]
  resources :faqs, only: [:destroy, :new, :create, :index, :edit, :update]

  # get '/404', to: "errors#not_found"
  # get '/422', to: "errors#unacceptable"
  # get '/500', to: "errors#internal_error"
end

app/models/stockist.rb
class Stockist < ApplicationRecord
  belongs_to :user
end

app/controllers/stockists_controller.rb
class StockistsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_product, only: [:edit, :update, :destroy]

  def index
    @stockists = Stockist.where("statut = ? AND category = ?", "active", "Stockist" ).order(created_at: :asc)
    @online_stores = Stockist.where("statut = ? AND category = ?", "active", "Online Store" ).order(created_at: :asc)
    @default_pic = "https://res.cloudinary.com/fogapothecary/image/upload/v1596465097/default_annonce_wxhhsp.png"
    @cities = City.all
  end

  def show
  end

  def new
    @stockist = Stockist.new
  end

  def create
    @stockist = Stockist.new(stockist_params)
    @stockist.user_id = current_user.id
    @stockist.statut = "active"
    if @stockist.save
      if @stockist.category == "Stockist"
        create_city
      end
      redirect_to stockists_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @stockist.update(stockist_params)
      create_city
      redirect_to stockists_path
    else
      render :edit
    end
  end

  def destroy
    @stockist.destroy
    redirect_to stockists_path
  end

  def create_city
    @stockists = Stockist.all
    @stockists.each do |stockist|
      unless stockist.city.nil?
        city = City.find_or_create_by( name: stockist.city.upcase)

      end
    end
  end

  private

  def stockist_params
    params.require(:stockist).permit(
      :category,
      :name,
      :city,
      :website,
    )
  end

  def set_product
    @stockist = Stockist.find(params[:id])
  end
end

app/views/stockists/edit.html.erb
<h1 class="text-center mt-5 mb-4">Update stockist</h1>
<div class="container center">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6 col-lg-6">
      <div class="center">
        <%= simple_form_for [@stockist] do |f| %>
          <%= f.input :category, collection: ["Stockist", "Online Store"] %>
          <%= f.input :name %>
          <%= f.input :city %>
          <%= f.input :website %>
          <%= f.submit "Update", class: "btn btn btn-yellow-mustard mb-2" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/stockists/index.html.erb
<div class="">
  <div class="d-flex my-5 align-items-center justify-content-center" style="background-color: rgba(196, 196, 196, 0.23); height: 216px">
    <h3 style="font-size: 30px">STOCKIST</h3>
  </div>
  <div class="container">
    <h3 class="mt-5 py-5 text-center" style="font-size: 20px">ONLINE STORE</h3>
    <div class="row">
      <% @online_stores.each do |stockist| %>
        <div class="col-12 col-md-5 offset-md-1">
          <div class='mb-5'>
            <%= link_to "https://#{stockist.website}", target: :blank, style:"text-decoration: none"    do  %>
              <!-- -->
              <div class="d-flex mb-2 align-items-center">
                <h3 class="mb-0" style="font-size: 18px; color: black"><%= stockist.name %></h3>
                <% if user_signed_in? %>
                  <%= link_to "", edit_stockist_path(stockist), class:"fas fa-edit ml-2", style:"font-size: 14px" %>
                  <h5 class="m-0" style="font-size: 14px">/</h5>
                  <%= link_to '', stockist_path(stockist), method: :delete, data: { confirm: 'Are you sure you want to delete this stockist ?'}, class:"fas fa-trash", style:"font-size: 14px"  %>
                <% end %>
              </div>
              <p style="font-size: 16px; color: black">www.<%= stockist.website %></p>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="border-top mt-5 py-5">
      <h3 class="my-5 text-center" style="font-size: 20px">STOCKIST</h3>
      <div class="row">
        <% @cities.each do |city| %>
          <% unless city.name.nil? || city.name == "" %>
            <div class="col-12 col-md-5 offset-md-1">
              <div class="d-flex mb-4 mt-5 align-items-center">
                <h3 class="m-0" style="font-size: 18px"><%= city.name.upcase %></h3>
                <% if user_signed_in? %>
                  <%= link_to '', city_path(city), method: :delete, data: { confirm: 'Are you sure you want to delete this stockist ?'}, class:"fas fa-trash ml-3", style:"font-size: 14px"  %>
                <% end %>
              </div>
              <% @stockists.each do |stockist| %>
                <% if stockist.city.upcase == city.name.upcase %>
                  <div class="mb-4">
                    <div class="d-flex mb-2 align-items-center">
                      <p class="mb-0" style="font-size: 16px"><strong></strong><%= stockist.name %></p>
                      <% if user_signed_in? %>
                        <%= link_to "", edit_stockist_path(stockist), class:"fas fa-edit ml-2", style:"font-size: 14px" %>
                        <h5 class="m-0" style="font-size: 14px">/</h5>
                        <%= link_to '', stockist_path(stockist), method: :delete, data: { confirm: 'Are you sure you want to delete this stockist ?'}, class:"fas fa-trash", style:"font-size: 14px"  %>
                      <% end %>
                    </div>
                    <p style="font-size: 16px"><%= stockist.website %></p>
                  </div>
                <% end %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <% if user_signed_in? %>
      <%= link_to "Add a city", new_city_path %>
    <% end %>
  </div>
</div>

app/views/stockists/new.html.erb
<h1 class="text-center mt-5 mb-4">List a new stockist</h1>
<div class="container center">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6 col-lg-6">
      <div class="center">
        <%= simple_form_for [@stockist] do |f| %>
          <%= f.input :category, collection: ["Stockist", "Online Store"] %>
          <%= f.input :name %>
          <%= f.input :city %>
          <%= f.input :website %>
          <%= f.submit "Create", class: "btn btn btn-yellow-mustard mb-2" %>
        <% end %>
      </div>
    </div>
  </div>
</div>