config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'page', to: 'pages#show'
  patch 'page', to: 'pages#update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pages, only: [:edit]

  resources :products, only: [:show, :new, :create, :index, :edit, :destroy,:update ]
  get '/products_in', to: "products#index_in", as: :products_in
  resources :journals, only: [:show, :new, :create, :index, :edit, :destroy,:update ]
  resources :philosophies, only: [:index, :edit, :update ]
  resources :stockists, only: [:new, :create, :index, :edit, :destroy,:update ]
  resources :cities, only: [:destroy, :new, :create]
  resources :faqs, only: [:destroy, :new, :create, :index, :edit, :update]

  # get '/404', to: "errors#not_found"
  # get '/422', to: "errors#unacceptable"
  # get '/500', to: "errors#internal_error"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_icones.html.erb
<div class="container-fluid my-5 py-5">
  <div class="row">
    <div class="col-6 col-md-2 offset-md-2">
      <% if @page.icone1_pic.attached? %>
        <%= cl_image_tag(@page.icone1_pic.key, class: "mb-4", style: "height:160px; object-position: center center; object-fit: cover; width: 100%") %>
        <p class="text-center"><%= @page.icone1_text %></p>
      <% else %>
        <%= cl_image_tag(@default_pic, class: "mb-4", style: "height:160px; object-position: center center; object-fit: cover; width: 100%") %>
        <p class="text-center"><%= @page.icone1_text %></p>
      <% end %>
    </div>
    <div class="col-6 col-md-2">
      <% if @page.icone2_pic.attached? %>
        <%= cl_image_tag(@page.icone2_pic.key, class: "mb-4", style: "height:160px; object-position: center center; object-fit: cover; width: 100%") %>
        <p class="text-center"><%= @page.icone2_text %></p>
      <% else %>
        <%= cl_image_tag(@default_pic, class: "mb-4", style: "height:160px; object-position: center center; object-fit: cover; width: 100%") %>
        <p class="text-center"><%= @page.icone2_text %></p>
      <% end %>
    </div>
    <div class="col-6 col-md-2">
      <% if @page.icone3_pic.attached? %>
        <%= cl_image_tag(@page.icone3_pic.key, class: "mb-4", style: "height:160px; object-position: center center; object-fit: cover; width: 100%") %>
        <p class="text-center"><%= @page.icone3_text %></p>
      <% else %>
        <%= cl_image_tag(@default_pic, class: "mb-4", style: "height:160px; object-position: center center; object-fit: cover; width: 100%") %>
        <p class="text-center"><%= @page.icone3_text %></p>
      <% end %>
    </div>
    <div class="col-6 col-md-2">
      <% if @page.icone4_pic.attached? %>
        <%= cl_image_tag(@page.icone4_pic.key, class: "mb-4", style: "height:160px; object-position: center center; object-fit: cover; width: 100%") %>
        <p class="text-center"><%= @page.icone4_text %></p>
      <% else %>
        <%= cl_image_tag(@default_pic, class: "mb-4", style: "height:160px; object-position: center center; object-fit: cover; width: 100%") %>
        <p class="text-center"><%= @page.icone4_text %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light navbar-lewagon text-center" style="background-color: #FAF7F3">
  <%= link_to root_path, class: "navbar-brand" do %>
    <!-- Laptop version -->
    <div class="hide-on-small">
      <%= cl_image_tag "https://res.cloudinary.com/fogapothecary/image/upload/v1596652960/LOGO_FOG_2020_cropped_ptm3co.png", style: "width:380px", class: "py-3" %>
    </div>
    <!-- Mobile version -->
    <div class="hide-on-large">
      <%= cl_image_tag "https://res.cloudinary.com/fogapothecary/image/upload/v1596652960/LOGO_FOG_2020_cropped_ptm3co.png", style: "width:220px", class: "py-3" %>
    </div>
  <% end %>
  <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active mx-4">
        <h5><%= link_to "Philosophy", philosophies_path, class: "nav-link", style:"font-size: 18px"%></h5>
      </li>
      <li class="nav-item active mx-4">
        <h5><%= link_to "Shop", products_path , class: "nav-link", style:"font-size: 18px"%></h5>
      </li>
      <li class="nav-item active mx-4">
        <h5><%= link_to "Stockist", stockists_path, class: "nav-link", style:"font-size: 18px"%></h5>
      </li>
      <li class="nav-item active mx-4">
        <h5><%= link_to "Ritual", journals_path, class: "nav-link", style:"font-size: 18px"%></h5>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "https://res.cloudinary.com/fogapothecary/image/upload/v1596465106/default_profile_kwhszl.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "List new product", new_product_path, class: "dropdown-item" %>
            <%= link_to "List new stockist", new_stockist_path, class: "dropdown-item" %>
            <%= link_to "List new ritual", new_journal_path, class: "dropdown-item" %>
            <%= link_to "Add a new FAQ", new_faq_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_slide.html.erb
<style>
  button {
    color: transparent;
    background-color: transparent;
    border: 0;
  }
</style>
<!-- Laptop version -->
<div class="hide-on-small ">
  <h3 class="text-center my-5" style="font-size: 30px">MOST POPULAR PRODUCTS</h3>
  <div class="slide-wrapper-laptop">
    <% @products.each do |product| %>
      <%= link_to products_path, style:"text-decoration: none; color: black" do %>
        <% if product.picture1.attached?  %>
          <div>
            <div class="slide-item">
              <%= cl_image_tag product.picture1.key, class: "rounded-top", style: "height:360px; object-position: center center; object-fit: cover; width: 100%"%>
            </div>
          </div>
        <% else %>
          <div>
            <div class="slide-item">
              <%= cl_image_tag @default_pic, class: "rounded-top slide-item", style: "height:360px; object-position: center center; object-fit: cover; width: 100%"%>
            </div>
          </div>
        <% end %>
        <p class="mt-3 text-center" style="font-size: 16px;"><%= product.name %></p>
      <% end %>
    <% end %>
  </div>
</div>
<!-- Mobile version -->
<div class="hide-on-large ">
  <h5 class="text-center my-5" style="">MOST POPULAR PRODUCTS</h5>
  <div class="slide-wrapper-mobile">
    <% @products.each do |product| %>
      <%= link_to products_path, style:"text-decoration: none; color: black" do %>
        <% if product.picture1.attached?  %>
          <div>
            <div class="slide-item">
              <%= cl_image_tag product.picture1.key, class: "rounded-top", style: "height:240px; object-position: center center; object-fit: cover; width: 100%"%>
            </div>
          </div>
        <% else %>
          <div>
            <div class="slide-item">
              <%= cl_image_tag @default_pic, class: "rounded-top slide-item", style: "height:240px; object-position: center center; object-fit: cover; width: 100%"%>
            </div>
          </div>
        <% end %>
        <p class="mt-3 text-center" style="font-size: 16px;"><%= product.name %></p>
      <% end %>
    <% end %>
  </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.9.2/min/tiny-slider.js"></script>
<!-- Laptop version -->
<script>
  var slider = tns({
    container: '.slide-wrapper-laptop',
    mouseDrag: true,
    swipeAngle: false,
    speed: 400,
    gutter: 10,
    autoplay: true,
    autoplayTimeout: 3500,
    controls: false,
    nav: false,
    responsive: {
      350: {
        items: 2,
        center: true,
      },
      500: {
        items: 4,
        center: true,
      }
    },
  });
</script>
<!-- Mobile version -->
<script>
  var slider = tns({
    container: '.slide-wrapper-mobile',
    mouseDrag: true,
    swipeAngle: false,
    speed: 400,
    gutter: 10,
    autoplay: true,
    autoplayTimeout: 3500,
    controls: false,
    nav: false,
    responsive: {
      350: {
        items: 2,
        center: true,
      },
      500: {
        items: 4,
        center: true,
      }
    },
  });
</script>