config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'page', to: 'pages#show'
  patch 'page', to: 'pages#update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pages, only: [:edit]

  resources :products, only: [:show, :new, :create, :index, :edit, :destroy,:update ]
  get '/products_in', to: "products#index_in", as: :products_in
  resources :journals, only: [:show, :new, :create, :index, :edit, :destroy,:update ]
  resources :philosophies, only: [:index, :edit, :update ]
  resources :stockists, only: [:new, :create, :index, :edit, :destroy,:update ]
  resources :cities, only: [:destroy, :new, :create]
  resources :faqs, only: [:destroy, :new, :create, :index, :edit, :update]

  # get '/404', to: "errors#not_found"
  # get '/422', to: "errors#unacceptable"
  # get '/500', to: "errors#internal_error"
end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :user
  has_one_attached :picture1
  has_one_attached :picture2
  has_one_attached :picture3
  has_one_attached :picture4
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_journal, only: [:edit, :show, :update, :destroy]

  def index
    @journals = Journal.where("statut = ?", "active" ).order(created_at: :asc)
    @default_pic = "https://res.cloudinary.com/fogapothecary/image/upload/v1596465097/default_annonce_wxhhsp.png"
  end

  def show
    @default_pic = "https://res.cloudinary.com/fogapothecary/image/upload/v1596465097/default_annonce_wxhhsp.png"
  end

  def new
    @journal = Journal.new
  end

  def create
    @journal = Journal.new(journal_params)
    @journal.user_id = current_user.id
    @journal.statut = "active"
    if @journal.save
      redirect_to journal_path(@journal)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @journal.update(journal_params)
      redirect_to journal_path(@journal)
    else
      render :edit
    end
  end

  def destroy
    @journal.statut = "deleted"
    @journal.save
    redirect_to journals_path
  end

  private

  def journal_params
    params.require(:journal).permit(
      :title,
      :description,
      :picture1,
      :picture2,
      :picture3,
      :picture4,
    )
  end

  def set_journal
    @journal = Journal.find(params[:id])
  end
end

app/views/journals/edit.html.erb
<h1 class="text-center mt-5 mb-4">List a new article</h1>
<div class="container center">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6 col-lg-6">
      <div class="center">
        <%= simple_form_for [@journal] do |f| %>
          <%= f.input :title %>
          <%= f.input :description %>
          <%= f.input :picture1, as: :file %>
          <%= f.input :picture2, as: :file %>
          <%= f.input :picture3, as: :file %>
          <%= f.input :picture4, as: :file %>
          <%= f.submit "Update", class: "btn btn btn-yellow-mustard mb-2" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/journals/index.html.erb
<div class="hide-on-small">
  <h3 class="hide-on-small text-center my-5" style="font-size: 30px">Ritual</h3>
  <div class="row mx-3 mb-5">
    <% @journals.each do |journal| %>
      <div class="col-12 col-md-4 my-4">
        <%= link_to journal_path(journal), style:"text-decoration: none" do %>
          <% if journal.picture1.attached? %>
            <div class="journal-card" style="height: 520px; background-size: cover; background-position: center; background-image:url('<%= cl_image_path journal.picture1.key, height: 520, width: 400, crop: :fill %>'); border-radius: 360px">
              <div class="container d-flex align-items-center justify-content-center" style="height: 520px">
                <h5 style="font-size: ; letter-spacing: 1px; text-align: center"><%= journal.title %></h5>
              </div>
            </div>
          <% else %>
            <div class="journal-card" style="height: 520px; background-size: cover; background-position: center; background-image:url('<%= cl_image_path @default_pic, height: 520, width: 400, crop: :fill %>'); border-radius: 360px">
              <div class="container d-flex align-items-center justify-content-center" style="height: 520px">
                <h5 style="font-size: ; letter-spacing: 1px; text-align: center"><%= journal.title %></h5>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<div class="hide-on-large">
  <h5 class=" text-center px-3 m-5">Ritual</h5>
  <div class="row mx-3 mb-5">
    <% @journals.each do |journal| %>
      <div class="col-12 col-md-4 my-4">
        <%= link_to journal_path(journal), style:"text-decoration: none" do %>
          <% if journal.picture1.attached? %>
            <div class="" style="height: 520px; background-size: cover; background-position: center; background-image:linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.3)), url('<%= cl_image_path journal.picture1.key, height: 520, width: 400, crop: :fill %>'); border-radius: 360px">
              <div class="container d-flex align-items-center justify-content-center" style="height: 520px">
                <h5 style="font-size: ; letter-spacing: 1px; text-align: center; color: white"><%= journal.title %></h5>
              </div>
            </div>
          <% else %>
            <div class="" style="height: 520px; background-size: cover; background-position: center; background-image:linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.3)), url('<%= cl_image_path @default_pic, height: 520, width: 400, crop: :fill %>'); border-radius: 360px">
              <div class="container d-flex align-items-center justify-content-center" style="height: 520px">
                <h5 style="font-size: ; letter-spacing: 1px; text-align: center; color: white"><%= journal.title %></h5>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/journals/new.html.erb
<h1 class="text-center mt-5 mb-4">List a new article</h1>
<div class="container center">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6 col-lg-6">
      <div class="center">
        <%= simple_form_for [@journal] do |f| %>
          <%= f.input :title %>
          <%= f.input :description %>
          <%= f.input :picture1, as: :file %>
          <%= f.input :picture2, as: :file %>
          <%= f.input :picture3, as: :file %>
          <%= f.input :picture4, as: :file %>
          <%= f.submit "Create", class: "btn btn btn-yellow-mustard mb-2" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/journals/show.html.erb
<!-- Laptop version -->
<div class="container my-5 hide-on-small">
  <div class="row">
    <div class="col-12 col-md-6">
      <% if @journal.picture1.attached? %>
        <%= cl_image_tag(@journal.picture1.key, class: "mb-4", style: "height:460px; object-position: center center; object-fit: cover; width: 100%") %>
      <% else %>
        <%= cl_image_tag(@default_pic, class: "mb-4", style: "height:460px; object-position: center center; object-fit: cover; width: 100%") %>
      <% end %>
      <% if @journal.picture2.attached? && @journal.picture3.attached? %>
        <div class="row">
          <div class="col-12 col-md-6">
            <%= cl_image_tag(@journal.picture2.key, class: "mb-4", style: "height:230px; object-position: center center; object-fit: cover; width: 100%") %>
          </div>
          <div class="col-12 col-md-6">
            <%= cl_image_tag(@journal.picture3.key, class: "mb-4", style: "height:230px; object-position: center center; object-fit: cover; width: 100%") %>
          </div>
        </div>
      <% end %>
      <% if @journal.picture4.attached? %>
        <%= cl_image_tag(@journal.picture4.key, class: "mb-4", style: "height:460px; object-position: center center; object-fit: cover; width: 100%") %>
      <% end %>
    </div>
    <div class="col-12 col-md-6 px-5">
      <div class="d-flex">
        <p style="font-size: 30px"><%= @journal.title %></p>
        <% if user_signed_in? %>
          <%= link_to "", edit_journal_path(@journal), class:"fas fa-edit ml-2 mt-2" %>
          <p style="font-size: 24px">/</p>
          <%= link_to '', journal_path(@journal), method: :delete, data: { confirm: 'Are you sure you cant to delete this journal ?'}, class:"fas fa-trash mt-2"  %>
        <% end %>
      </div>
      <p ><%= simple_format(@journal.description, style:"font-size: 12px") %></p>
    </div>
  </div>
</div>
<!-- Mobile version -->
<div class="container mb-5 hide-on-large">
  <div class="row">
    <div class="col-12 col-md-6 p-5">
      <div class="d-flex">
        <p style="font-size: 30px"><%= @journal.title %></p>
        <% if user_signed_in? %>
          <%= link_to "", edit_journal_path(@journal), class:"fas fa-edit ml-2 mt-2" %>
          <p style="font-size: 24px">/</p>
          <%= link_to '', journal_path(@journal), method: :delete, data: { confirm: 'Are you sure you cant to delete this journal ?'}, class:"fas fa-trash mt-2"  %>
        <% end %>
      </div>
      <p><%= simple_format(@journal.description,  style:"font-size: 12px") %></p>
    </div>
    <div class="col-12 col-md-6">
      <% if @journal.picture1.attached? %>
        <%= cl_image_tag(@journal.picture1.key, class: "mb-4", style: "height:260px; object-position: center center; object-fit: cover; width: 100%") %>
      <% else %>
        <%= cl_image_tag(@default_pic, class: "mb-4", style: "height:260px; object-position: center center; object-fit: cover; width: 100%") %>
      <% end %>
      <% if @journal.picture2.attached? %>
        <%= cl_image_tag(@journal.picture2.key, class: "mb-4", style: "height:260px; object-position: center center; object-fit: cover; width: 100%") %>
      <% end %>
      <% if @journal.picture3.attached? %>
        <%= cl_image_tag(@journal.picture3.key, class: "mb-4", style: "height:260px; object-position: center center; object-fit: cover; width: 100%") %>
      <% end %>
      <% if @journal.picture4.attached? %>
        <%= cl_image_tag(@journal.picture4.key, class: "mb-4", style: "height:260px; object-position: center center; object-fit: cover; width: 100%") %>
      <% end %>
    </div>
  </div>
</div>